import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import * as schema from "./schema";

/**
 * The Drizzle DB instance used across the app (the inner value returned by
 * `drizzle(...)`, NOT the `{ db, sqlite }` bag). Callers receive the drizzle
 * client; the native handle stays inside `createDb` for shutdown.
 */
export type DB = ReturnType<typeof drizzle<typeof schema>>;

export type CreateDbOptions = {
	/** File path or `:memory:`. */
	readonly path: string;
	/** Folder containing the drizzle generated migrations (default `./migrations`). */
	readonly migrationsFolder?: string;
	/** When true, run pending migrations on boot (default `true`). */
	readonly runMigrations?: boolean;
};

/**
 * Boot a Drizzle (better-sqlite3) connection. Applies pending migrations
 * generated by `drizzle-kit generate` (see ADR-0007 — migrations only via
 * the ORM; no hand-written SQL).
 *
 * Returns `{ db, native }` so callers can close the native connection at
 * shutdown if desired; the type passed around the app is {@link DB}.
 */
export function createDb(options: CreateDbOptions): {
	db: DB;
	native: Database.Database;
} {
	const native = new Database(options.path);
	native.pragma("journal_mode = WAL");
	native.pragma("foreign_keys = ON");

	const db: DB = drizzle(native, { schema });

	if (options.runMigrations ?? true) {
		migrate(db, {
			migrationsFolder: options.migrationsFolder ?? "./migrations",
		});
	}

	return { db, native };
}
